version: '3.3'

services:

  web:
    image: nginx:latest 
    restart: always 
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./data/nginx/redmine-fr.conf:/etc/nginx/conf.d/default.conf 
      - ./data/letsencrypt:/etc/letsencrypt 
      - /tmp/acme_challenge:/tmp/acme_challenge 
    networks: 
      - app
    restart: always

networks: 
  app:
    driver: bridge

