FROM python:3
ENV TZ="Europe/Moscow"
WORKDIR /usr/src/app
RUN mkdir ./dockerdata
#RUN addgroup --system app && adduser --system --group app
#RUN chown -R app:app ./dockerdata
#USER app

COPY requirements.txt ./
RUN pip install --root-user-action=ignore requests --upgrade pip
RUN pip install --root-user-action=ignore requests --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "-u", "./chatbot.py"]
